import { ThemeConfig } from "antd";

export const theme: ThemeConfig = {
  token: {
    colorText: "#eee",
    // colorPrimary: "#bbb",
    // colorError: "orange",
    // colorLink: "yellow",
    // colorLinkHover: "green",
    // colorTextSecondary: "blue",
    // colorTextTertiary: "#eee",
    // colorTextQuaternary: "purple",
    // colorWarning: "magenta",
  },
  components: {
    // Typography: {
    //   colorPrimary: "red",
    //   colorLink: "red",
    //   colorLinkHover: "red",
    //   colorText: "#eee",
    //   colorTextSecondary: "red",
    //   colorTextTertiary: "red",
    //   colorTextQuaternary: "red",
    //   colorWarning: "red",
    // },
    Input: {
      fontSize: 16,
      paddingBlock: 6,
      paddingInline: 10,
      // controlOutlineWidth: 3,
      // controlOutline: "var(--blue-9)",
      lineWidth: 1,
      borderRadius: 3,
      colorBorder: "#777",
      hoverBorderColor: "#bbb",
      activeBorderColor: "var(--blue-9)",
      colorTextPlaceholder: "#aaa",
      colorBgContainer: "#0d0c22",

      // colorPrimary: "red",
      // colorLink: "red",
      // colorLinkHover: "red",
      // colorText: "#eee",
      // colorTextSecondary: "red",
      // colorTextTertiary: "red",
      // colorTextQuaternary: "red",
      // colorWarning: "red",
    },
    Select: {
      // fontSize: 16,
      // paddingBlock: 6,
      // paddingInline: 10,
      // controlOutlineWidth: 3,
      // controlOutline: "var(--blue-9)",
      // lineWidth: 1,
      colorPrimaryHover: "#bbb",
      // colorBorderBg: "red",
      borderRadiusLG: 3, // input框
      borderRadius: 5, // 選到的選項
      colorText: "#eee",
      colorBorder: "#777",
      colorBgElevated: "#0d0c22",
      multipleItemBorderColor: "#eee",
      boxShadow: "0 0 0 1px #0d0c22",
      optionSelectedBg: "var(--blue-7)",
      optionActiveBg: "var(--blue-5)",
      colorBgContainer: "#0d0c22",
    },
    Popover: {
      borderRadius: 50,
      borderRadiusOuter: 50,
      borderRadiusLG: 50,
    },
  },
};
