import type { Metadata } from "next";
import { Roboto, Noto_Sans_TC } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import "@mdxeditor/editor/style.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const noto_sans_tc_init = Noto_Sans_TC({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-noto-sans-tc",
});

const roboto_init = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: {
    default: "Next.js 14 Homepage",
    template: "%s | Next.js 14",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto_sans_tc_init.variable} ${roboto_init.variable}`}>
        <div className="container">
          <AntdRegistry>
            <Navbar />
            {children}
            <Footer />
          </AntdRegistry>
        </div>
      </body>
    </html>
  );
}
